# Generated by Django 5.2.4 on 2025-08-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_expiry_date_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('low_stock', 'Low Stock')], default='available', max_length=20),
        ),
    ]
